import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import CreatePostWizard from "~/components/CreatePostWizard";
import LoadingSpinner from "~/components/LoadingSpinner";
import PostView from "~/components/PostView";

import { api } from "~/utils/api";

const ProfilePage: NextPage = () => {
  const { data, isLoading } = api.profile.getUserByUsername.useQuery({
    username: "mikeblackwood",
  });

  if (isLoading) {
    return (
      <div>
        <LoadingSpinner />
      </div>
    );
  }

  if (!data) {
    return <div>Error</div>;
  }

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center ">
        {/* <div className="container h-screen w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex justify-end border-b border-slate-400">
            <div className="flex h-10 pr-2">
              {!isSignedIn && <SignInButton />}
              {isSignedIn && <SignOutButton />}
            </div>
          </div>
          <div>{isSignedIn && <CreatePostWizard />}</div>
          <Feed />
        </div> */}
        <div>{data.username}</div>
      </main>
    </>
  );
};

export default ProfilePage;
