import { SignIn, SignInButton, SignOutButton, SignUp, useUser } from "@clerk/nextjs";
import { map } from "@trpc/server/observable";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const {isLoading, data: posts, error} = api.post.getAll.useQuery();
  console.log(posts)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
        
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {!user.isSignedIn && <SignInButton/>}
            {!!user.isLoaded && <SignOutButton/>}
          </div>
          
          {posts?.map((post) => {
            return <div key={post.id}>{post.content}</div>
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
