import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import CreatePostWizard from "~/components/CreatePostWizard";
import LoadingSpinner from "~/components/LoadingSpinner";
import PostView from "~/components/PostView";

import { api } from "~/utils/api";

const SinglePostPage: NextPage = () => {
  const { user, isLoaded: userLoaded, isSignedIn } = useUser();
  // Prefetching
  api.post.getAll.useQuery();
  if (!userLoaded) {
    return (
      <div className="flex h-screen w-full items-center justify-center align-middle">
        <LoadingSpinner />
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center ">
        <div>Single Post Page</div>
      </main>
    </>
  );
};

export default SinglePostPage;
