name: CI

env:
  DATABASE_URL: "https://fake.com"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
          scope: "@my-scope"
      - name: Install dependencies
        run: pnpm install
      - name: Check TypeScript
        run: pnpm run check-ts
      - name: Run lint
        run: pnpm run lint
